handlers:
- url: '/'
  static_files: 'index.html index.htm readme.txt readme.markdown readme.md'
  upload: '.*'
- url: '/'
  static_dir: '/'
- url: '/(.*?)/'
  static_files: '/(.*?)/'
  upload:  '/(.*?)/'
