handlers:
- url: '/'
  static_files: 'index.html'
  upload: '.*'
- url: '/'
  static_dir: '/'
- url: '/(20\d\d)/((0[1-9]|[0-1][0-2]))/((0[1-9]|[1-2][0-9]|3[01]))/'
  static_files: '/\1/\2/\3/index\.html'
  upload: '/(20\d\d)/((0[1-9]|[0-1][0-2]))/((0[1-9]|[1-2][0-9]|3[01]))/'
