handlers:
- url: '/'
  static_files: 'index.html'
  upload: '.*'
- url: '/'
  static_dir: '/'
- url: '/(.*)/(.*)/(.*)/(.*)/'
  static_files: '/\1/\2/\3/\4/index\.html'
  upload: '/(.*)/(.*)/(.*)/(.*)/'
